kafka:
  bootstrap:
    servers: "10.19.93.228:9092"
  input:
    topic: "demo-flink-01"
  output:
    topic: "output-topic"
  group:
    id: "my-group"

checkpoint:
  interval: 10000
  min:
    pause: 5000
  timeout: 60000

# Nacos Configuration
nacos:
  server-addr: "10.19.93.240:8848"
  username: "admin"
  password: "admin1001"
  namespace: "zfl"
  data-id: "test-flink-job-kafka.yml"
  group: "DEFAULT_GROUP"
  file-extension: "yml"

